DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS semantic_references;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS anchors;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS cache_meta;
