use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::Path;

use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};

use super::LoadedWorkspace;

const MANIFEST: &str = ".plumb-vdir";

pub(super) fn export_vdir(
    loaded: &LoadedWorkspace,
    output: &Path,
    now: DateTime<Utc>,
) -> Result<(), String> {
    ensure_managed_output(output)?;
    let parent = output
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
    let name = output
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("calendar");
    let staging = parent.join(format!(".{name}.plumb-staging-{}", std::process::id()));
    if staging.exists() {
        std::fs::remove_dir_all(&staging)
            .map_err(|error| format!("cannot clear {}: {error}", staging.display()))?;
    }
    std::fs::create_dir(&staging)
        .map_err(|error| format!("cannot create {}: {error}", staging.display()))?;
    std::fs::write(staging.join(MANIFEST), "generated by plumb\n")
        .map_err(|error| format!("cannot write vdir manifest: {error}"))?;

    let mut uids = HashSet::new();
    let mut events = loaded
        .workspace
        .documents()
        .filter_map(|entry| entry.current.as_ref().map(|current| (entry, current)))
        .flat_map(|(entry, current)| {
            current
                .output
                .events
                .events
                .iter()
                .map(move |event| (entry, event))
        })
        .collect::<Vec<_>>();
    events.sort_by(|(left_entry, left), (right_entry, right)| {
        left.start
            .as_ref()
            .map(|field| field.value.as_str())
            .cmp(&right.start.as_ref().map(|field| field.value.as_str()))
            .then(left_entry.path.cmp(&right_entry.path))
            .then(left.range.start.cmp(&right.range.start))
    });

    for (entry, event) in events {
        let uid = event
            .uid
            .as_ref()
            .filter(|uid| !uid.value.is_empty())
            .ok_or_else(|| {
                format!(
                    "event '{}' in {} has no calendar UID",
                    event.title,
                    entry.path.display()
                )
            })?;
        if !uids.insert(uid.value.clone()) {
            return Err(format!("duplicate event UID '{}'", uid.value));
        }
        let start = event.start_datetime().ok_or_else(|| {
            format!(
                "event '{}' in {} has no valid start",
                event.title,
                entry.path.display()
            )
        })?;
        let end = event.end_datetime();
        if end.is_some_and(|end| end <= start) {
            return Err(format!(
                "event '{}' in {} has an invalid interval",
                event.title,
                entry.path.display()
            ));
        }
        let ical = render_event(
            event,
            start.with_timezone(&Utc),
            end.map(|end| end.with_timezone(&Utc)),
            now,
        );
        let filename = format!("{}.ics", hex_digest(uid.value.as_bytes()));
        std::fs::write(staging.join(filename), ical)
            .map_err(|error| format!("cannot write generated calendar item: {error}"))?;
    }

    replace_directory(output, &staging)
}

fn ensure_managed_output(output: &Path) -> Result<(), String> {
    if !output.exists() {
        return Ok(());
    }
    if !output.is_dir() {
        return Err(format!(
            "vdir output is not a directory: {}",
            output.display()
        ));
    }
    let mut entries = std::fs::read_dir(output)
        .map_err(|error| format!("cannot read {}: {error}", output.display()))?;
    if entries.next().is_some() && !output.join(MANIFEST).is_file() {
        return Err(format!(
            "refusing to replace unmanaged nonempty directory {}",
            output.display()
        ));
    }
    Ok(())
}

fn replace_directory(output: &Path, staging: &Path) -> Result<(), String> {
    let backup = output.with_extension(format!("plumb-backup-{}", std::process::id()));
    if backup.exists() {
        std::fs::remove_dir_all(&backup)
            .map_err(|error| format!("cannot clear {}: {error}", backup.display()))?;
    }
    if output.exists() {
        std::fs::rename(output, &backup)
            .map_err(|error| format!("cannot stage existing vdir: {error}"))?;
    }
    if let Err(error) = std::fs::rename(staging, output) {
        if backup.exists() {
            let _ = std::fs::rename(&backup, output);
        }
        return Err(format!("cannot install generated vdir: {error}"));
    }
    if backup.exists() {
        std::fs::remove_dir_all(&backup)
            .map_err(|error| format!("cannot remove old vdir: {error}"))?;
    }
    Ok(())
}

fn render_event(
    event: &plumb_extensions::EventRecord,
    start: DateTime<Utc>,
    end: Option<DateTime<Utc>>,
    now: DateTime<Utc>,
) -> String {
    let mut lines = vec![
        "BEGIN:VCALENDAR".to_string(),
        "VERSION:2.0".to_string(),
        "PRODID:-//plumb//calendar//EN".to_string(),
        "CALSCALE:GREGORIAN".to_string(),
        "BEGIN:VEVENT".to_string(),
        format!(
            "UID:{}",
            escape_text(&event.uid.as_ref().expect("validated UID").value)
        ),
        format!("DTSTAMP:{}", ical_datetime(now)),
        format!("DTSTART:{}", ical_datetime(start)),
    ];
    if let Some(end) = end {
        lines.push(format!("DTEND:{}", ical_datetime(end)));
    }
    lines.push(format!("SUMMARY:{}", escape_text(&event.title)));
    lines.push(format!("DESCRIPTION:{}", escape_text(&event.details)));
    for task in &event.tasks {
        lines.push(format!("X-PLUMB-TASK:{}", escape_text(&task.source)));
    }
    lines.extend(["END:VEVENT".to_string(), "END:VCALENDAR".to_string()]);
    let mut output = String::new();
    for line in lines {
        let _ = write!(output, "{}\r\n", fold_line(&line));
    }
    output
}

fn escape_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace(';', "\\;")
        .replace(',', "\\,")
        .replace("\r\n", "\\n")
        .replace(['\r', '\n'], "\\n")
}

fn ical_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y%m%dT%H%M%SZ").to_string()
}

fn fold_line(line: &str) -> String {
    let mut output = String::new();
    let mut width = 0usize;
    for character in line.chars() {
        let bytes = character.len_utf8();
        if width + bytes > 75 {
            output.push_str("\r\n ");
            width = 1;
        }
        output.push(character);
        width += bytes;
    }
    output
}

fn hex_digest(value: &[u8]) -> String {
    let digest = Sha256::digest(value);
    let mut output = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(output, "{byte:02x}");
    }
    output
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use chrono::TimeZone;

    use super::*;
    use crate::LoadedWorkspace;
    use plumb_workspace::Workspace;

    #[test]
    fn exports_managed_vdir_with_escaped_folded_crlf_events_and_stale_cleanup() {
        let root = std::env::temp_dir().join(format!(
            "plumb-event-vdir-test-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let output = root.join("calendar");
        std::fs::create_dir_all(&root).unwrap();
        let source = "`-{.event uid=\"review@example\" start=\"2026-07-30T14:00:00+08:00\" end=\"2026-07-30T15:30:00+08:00\" tasks=\"#write\"} Review, parser; semantics with a deliberately long summary that must be folded safely\n  `note First line\n";
        let mut workspace = Workspace::new();
        workspace.insert(root.join("events.plumb"), 1, source);
        let loaded = LoadedWorkspace {
            workspace,
            texts: HashMap::new(),
        };
        let now = Utc.with_ymd_and_hms(2026, 7, 30, 0, 0, 0).unwrap();
        export_vdir(&loaded, &output, now).unwrap();
        let item = std::fs::read_dir(&output)
            .unwrap()
            .filter_map(Result::ok)
            .find(|entry| {
                entry
                    .path()
                    .extension()
                    .is_some_and(|extension| extension == "ics")
            })
            .unwrap();
        let ical = std::fs::read_to_string(item.path()).unwrap();
        assert!(ical.contains("DTSTART:20260730T060000Z\r\n"), "{ical:?}");
        assert!(ical.contains("DTEND:20260730T073000Z\r\n"), "{ical:?}");
        assert!(ical.contains("SUMMARY:Review\\, parser\\;"), "{ical:?}");
        assert!(ical.contains("\r\n "), "{ical:?}");
        assert!(ical.contains("X-PLUMB-TASK:#write\r\n"), "{ical:?}");
        std::fs::write(output.join("stale.ics"), "stale").unwrap();
        export_vdir(&loaded, &output, now).unwrap();
        assert!(!output.join("stale.ics").exists());
        std::fs::remove_dir_all(root).unwrap();
    }
}
