use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Component, Path};

use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};

use super::LoadedWorkspace;

const MANIFEST: &str = ".plumb-vdir";

pub(super) fn export_vdir(loaded: &LoadedWorkspace, output: &Path) -> Result<(), String> {
    ensure_managed_output(output)?;
    let desired = desired_events(loaded)?;
    reconcile_vdir(output, &desired)
}

fn desired_events(loaded: &LoadedWorkspace) -> Result<BTreeMap<String, String>, String> {
    let mut events = loaded
        .workspace
        .documents()
        .filter_map(|entry| entry.current.as_ref().map(|current| (entry, current)))
        .flat_map(|(entry, current)| {
            current
                .output
                .events
                .events
                .iter()
                .map(move |event| (entry, event))
        })
        .collect::<Vec<_>>();
    events.sort_by(|(left_entry, left), (right_entry, right)| {
        left.at
            .as_ref()
            .or(left.start.as_ref())
            .map(|field| field.value.as_str())
            .cmp(
                &right
                    .at
                    .as_ref()
                    .or(right.start.as_ref())
                    .map(|field| field.value.as_str()),
            )
            .then(left_entry.path.cmp(&right_entry.path))
            .then(left.range.start.cmp(&right.range.start))
    });

    let mut desired = BTreeMap::new();
    for (entry, event) in events {
        let uid = derived_uid(loaded, &entry.path, event);
        let start = event.sort_datetime().ok_or_else(|| {
            format!(
                "event '{}' in {} has no valid time",
                event.title,
                entry.path.display()
            )
        })?;
        let end = event.end_datetime();
        if event.is_running() {
            return Err(format!(
                "event '{}' in {} is still running",
                event.title,
                entry.path.display()
            ));
        }
        if end.is_some_and(|end| end <= start) {
            return Err(format!(
                "event '{}' in {} has an invalid interval",
                event.title,
                entry.path.display()
            ));
        }
        let start = start.with_timezone(&Utc);
        let tasks = loaded
            .workspace
            .event_task_references(&entry.path, event)
            .into_iter()
            .map(|task| task.source)
            .collect::<Vec<_>>();
        let ical = render_event(
            event,
            &uid,
            start,
            end.map(|end| end.with_timezone(&Utc)),
            &tasks,
        );
        let filename = format!("{uid}.ics");
        if desired.insert(filename, ical).is_some() {
            return Err(format!(
                "events in {} have duplicate calendar identity for schedule '{}' and title '{}'",
                entry.path.display(),
                event.when.as_ref().map_or("", |field| field.value.as_str()),
                event.title
            ));
        }
    }
    Ok(desired)
}

fn ensure_managed_output(output: &Path) -> Result<(), String> {
    if !output.exists() {
        return Ok(());
    }
    if !output.is_dir() {
        return Err(format!(
            "vdir output is not a directory: {}",
            output.display()
        ));
    }
    let mut entries = std::fs::read_dir(output)
        .map_err(|error| format!("cannot read {}: {error}", output.display()))?;
    if entries.next().is_some() && !output.join(MANIFEST).is_file() {
        return Err(format!(
            "refusing to replace unmanaged nonempty directory {}",
            output.display()
        ));
    }
    Ok(())
}

fn reconcile_vdir(output: &Path, desired: &BTreeMap<String, String>) -> Result<(), String> {
    std::fs::create_dir_all(output)
        .map_err(|error| format!("cannot create {}: {error}", output.display()))?;
    let manifest = output.join(MANIFEST);
    if !manifest.exists() {
        std::fs::write(&manifest, "generated by plumb\n")
            .map_err(|error| format!("cannot write vdir manifest: {error}"))?;
    }

    let mut existing = BTreeMap::new();
    for entry in std::fs::read_dir(output)
        .map_err(|error| format!("cannot read {}: {error}", output.display()))?
    {
        let entry =
            entry.map_err(|error| format!("cannot enumerate {}: {error}", output.display()))?;
        if entry
            .path()
            .extension()
            .is_some_and(|extension| extension == "ics")
        {
            existing.insert(
                entry.file_name().to_string_lossy().into_owned(),
                entry.path(),
            );
        }
    }

    for (filename, contents) in desired {
        let path = output.join(filename);
        if let Some(existing_path) = existing.get(filename) {
            let old = std::fs::read_to_string(existing_path)
                .map_err(|error| format!("cannot read {}: {error}", existing_path.display()))?;
            if old == *contents {
                continue;
            }
        }
        atomic_write(&path, contents)?;
    }

    for (filename, path) in existing {
        if !desired.contains_key(&filename) {
            std::fs::remove_file(&path)
                .map_err(|error| format!("cannot remove stale {}: {error}", path.display()))?;
        }
    }
    Ok(())
}

fn atomic_write(path: &Path, contents: &str) -> Result<(), String> {
    let filename = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("event.ics");
    let temporary = path.with_file_name(format!(".{filename}.tmp-{}", std::process::id()));
    std::fs::write(&temporary, contents)
        .map_err(|error| format!("cannot write {}: {error}", temporary.display()))?;
    std::fs::rename(&temporary, path).map_err(|error| {
        let _ = std::fs::remove_file(&temporary);
        format!("cannot install {}: {error}", path.display())
    })
}

fn render_event(
    event: &plumb_extensions::EventRecord,
    uid: &str,
    start: DateTime<Utc>,
    end: Option<DateTime<Utc>>,
    tasks: &[String],
) -> String {
    let mut lines = vec![
        "BEGIN:VCALENDAR".to_string(),
        "VERSION:2.0".to_string(),
        "PRODID:-//plumb//calendar//EN".to_string(),
        "CALSCALE:GREGORIAN".to_string(),
        "BEGIN:VEVENT".to_string(),
        format!("UID:{}", escape_text(uid)),
        format!("DTSTAMP:{}", ical_datetime(start)),
        format!("DTSTART:{}", ical_datetime(start)),
    ];
    if let Some(end) = end {
        lines.push(format!("DTEND:{}", ical_datetime(end)));
    }
    lines.push(format!("SUMMARY:{}", escape_text(&event.title)));
    lines.push(format!("DESCRIPTION:{}", escape_text(&event.details)));
    for task in tasks {
        lines.push(format!("X-PLUMB-TASK:{}", escape_text(task)));
    }
    lines.extend(["END:VEVENT".to_string(), "END:VCALENDAR".to_string()]);
    let mut output = String::new();
    for line in lines {
        let _ = write!(output, "{}\r\n", fold_line(&line));
    }
    output
}

fn derived_uid(
    loaded: &LoadedWorkspace,
    path: &Path,
    event: &plumb_extensions::EventRecord,
) -> String {
    let relative = path.strip_prefix(&loaded.root).unwrap_or(path);
    let relative = relative
        .components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy()),
            Component::ParentDir => Some("..".into()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/");
    let identity = format!(
        "{}\0{}\0{}",
        relative,
        event.when.as_ref().map_or("", |field| field.value.as_str()),
        event.title
    );
    format!("{}@plumb.local", hex_digest(identity.as_bytes()))
}

fn escape_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace(';', "\\;")
        .replace(',', "\\,")
        .replace("\r\n", "\\n")
        .replace(['\r', '\n'], "\\n")
}

fn ical_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y%m%dT%H%M%SZ").to_string()
}

fn fold_line(line: &str) -> String {
    let mut output = String::new();
    let mut width = 0usize;
    for character in line.chars() {
        let bytes = character.len_utf8();
        if width + bytes > 75 {
            output.push_str("\r\n ");
            width = 1;
        }
        output.push(character);
        width += bytes;
    }
    output
}

fn hex_digest(value: &[u8]) -> String {
    let digest = Sha256::digest(value);
    let mut output = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(output, "{byte:02x}");
    }
    output
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;
    use crate::LoadedWorkspace;
    use plumb_workspace::Workspace;

    #[test]
    fn exports_managed_vdir_with_escaped_folded_crlf_events_and_stale_cleanup() {
        let root = std::env::temp_dir().join(format!(
            "plumb-event-vdir-test-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let output = root.join("calendar");
        std::fs::create_dir_all(&root).unwrap();
        let source = "{\n  `: date 2026-07-30\n  `: timezone +08:00\n}\n\n`- 14:00--15:30 Review, parser; semantics with a deliberately long summary that must be folded safely\n   {\n     `- event\n     `: tasks #write\n   }\n\n   `note First line\n";
        let mut workspace = Workspace::new();
        workspace.insert(root.join("events.plumb"), 1, source);
        let mut loaded = LoadedWorkspace {
            root: root.clone(),
            workspace,
            texts: HashMap::new(),
        };
        let expected_filename = desired_events(&loaded).unwrap().into_keys().next().unwrap();
        export_vdir(&loaded, &output).unwrap();
        let item = std::fs::read_dir(&output)
            .unwrap()
            .filter_map(Result::ok)
            .find(|entry| {
                entry
                    .path()
                    .extension()
                    .is_some_and(|extension| extension == "ics")
            })
            .unwrap();
        let ical = std::fs::read_to_string(item.path()).unwrap();
        let unfolded = ical.replace("\r\n ", "");
        let uid = unfolded
            .lines()
            .find_map(|line| line.strip_prefix("UID:"))
            .unwrap();
        assert_eq!(item.file_name().to_string_lossy(), expected_filename);
        assert_eq!(item.file_name().to_string_lossy(), format!("{uid}.ics"));
        assert!(ical.contains("UID:"), "{ical:?}");
        assert!(unfolded.contains("@plumb.local\r\n"), "{ical:?}");
        assert!(ical.contains("DTSTAMP:20260730T060000Z\r\n"), "{ical:?}");
        assert!(ical.contains("DTSTART:20260730T060000Z\r\n"), "{ical:?}");
        assert!(ical.contains("DTEND:20260730T073000Z\r\n"), "{ical:?}");
        assert!(ical.contains("SUMMARY:Review\\, parser\\;"), "{ical:?}");
        assert!(ical.contains("\r\n "), "{ical:?}");
        assert!(ical.contains("X-PLUMB-TASK:#write\r\n"), "{ical:?}");
        std::fs::write(output.join("stale.ics"), "stale").unwrap();
        export_vdir(&loaded, &output).unwrap();
        assert_eq!(std::fs::read_to_string(item.path()).unwrap(), ical);
        assert!(!output.join("stale.ics").exists());

        loaded.workspace.insert(
            root.join("events.plumb"),
            2,
            source.replace("First line", "Updated detail"),
        );
        export_vdir(&loaded, &output).unwrap();
        let updated = std::fs::read_to_string(item.path()).unwrap();
        assert!(
            updated.contains("DESCRIPTION:Updated detail"),
            "{updated:?}"
        );
        assert_eq!(
            std::fs::read_dir(&output)
                .unwrap()
                .filter_map(Result::ok)
                .filter(|entry| entry.path().extension().is_some_and(|value| value == "ics"))
                .count(),
            1
        );
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn exports_point_events_and_rejects_missing_times() {
        let root = std::env::temp_dir().join(format!(
            "plumb-event-time-shape-test-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir_all(&root).unwrap();
        let mut workspace = Workspace::new();
        workspace.insert(
            root.join("point.plumb"),
            1,
            "{\n  `: date 2026-07-30\n  `: timezone +08:00\n}\n\n`- 14:00 Reminder\n   {\n     `- event\n   }\n",
        );
        let loaded = LoadedWorkspace {
            root: root.clone(),
            workspace,
            texts: HashMap::new(),
        };
        let point_output = root.join("point-calendar");
        export_vdir(&loaded, &point_output).unwrap();
        let point = std::fs::read_dir(&point_output)
            .unwrap()
            .filter_map(Result::ok)
            .find(|entry| entry.path().extension().is_some_and(|value| value == "ics"))
            .map(|entry| std::fs::read_to_string(entry.path()).unwrap())
            .unwrap();
        assert!(point.contains("DTSTART:20260730T060000Z\r\n"));
        assert!(!point.contains("DTEND:"));

        let mut workspace = Workspace::new();
        workspace.insert(
            root.join("running.plumb"),
            1,
            "{\n  `: date 2026-07-30\n  `: timezone +08:00\n}\n\n`- Work\n   {\n     `- event\n   }\n",
        );
        let loaded = LoadedWorkspace {
            root: root.clone(),
            workspace,
            texts: HashMap::new(),
        };
        assert!(export_vdir(&loaded, &root.join("running-calendar"))
            .unwrap_err()
            .contains("has no valid time"));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn uid_and_ical_are_independent_of_absolute_root_and_source_range() {
        let base = std::env::temp_dir().join(format!(
            "plumb-event-portable-id-test-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let first_root = base.join("device-a");
        let second_root = base.join("device-b");
        let source = "{\n  `: date 2026-07-30\n  `: timezone +08:00\n}\n\n`- 14:00 Review\n   {\n     `- event\n   }\n";
        let shifted_source = source.replacen(
            "\n\n`- 14:00 Review",
            "\n\nA preceding paragraph.\n\n`- 14:00 Review",
            1,
        );

        let first = loaded_with_source(&first_root, "notes/events.plumb", source);
        let second = loaded_with_source(&second_root, "notes/events.plumb", &shifted_source);
        assert_eq!(
            desired_events(&first).unwrap(),
            desired_events(&second).unwrap()
        );
        std::fs::remove_dir_all(base).unwrap();
    }

    #[test]
    fn rejects_duplicate_path_schedule_and_title_identities() {
        let root = std::env::temp_dir().join(format!(
            "plumb-event-duplicate-id-test-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let source = "{\n  `: date 2026-07-30\n  `: timezone +08:00\n}\n\n`- 14:00 Review\n   {\n     `- event\n   }\n`- 14:00 Review\n   {\n     `- event\n   }\n";
        let loaded = loaded_with_source(&root, "events.plumb", source);
        assert!(desired_events(&loaded)
            .unwrap_err()
            .contains("duplicate calendar identity"));
        std::fs::remove_dir_all(root).unwrap();
    }

    fn loaded_with_source(root: &Path, relative: &str, source: &str) -> LoadedWorkspace {
        std::fs::create_dir_all(root.join("notes")).unwrap();
        let mut workspace = Workspace::new();
        workspace.insert(root.join(relative), 1, source);
        LoadedWorkspace {
            root: root.to_path_buf(),
            workspace,
            texts: HashMap::new(),
        }
    }
}
