[package]
name = "plumb-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cel.workspace = true
chrono.workspace = true
ignore.workspace = true
plumb-core = { path = "../plumb-core" }
plumb-edit = { path = "../plumb-edit" }
plumb-extensions = { path = "../plumb-extensions" }
plumb-format = { path = "../plumb-format" }
uuid.workspace = true
