[package]
name = "plumb-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
cel.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
ignore.workspace = true
libsqlite3-sys.workspace = true
plumb-syntax = { path = "../plumb-syntax" }
plumb-edit = { path = "../plumb-edit" }
plumb-semantics = { path = "../plumb-semantics" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion.workspace = true
plumb-format = { path = "../plumb-format" }
tempfile = "3"

[[bench]]
name = "semantic_store"
harness = false
