[package]
name = "plumb-import"
version.workspace = true
edition.workspace = true
license.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[dependencies]
pandoc_types.workspace = true
plumb-syntax = { path = "../plumb-syntax" }
plumb-edit = { path = "../plumb-edit" }
serde_json.workspace = true
