[package]
name = "plumb-semantics"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
profile-semantic-stages = []

[dependencies]
plumb-edit = { path = "../plumb-edit" }
plumb-syntax = { path = "../plumb-syntax" }
chrono.workspace = true
serde.workspace = true
url.workspace = true
