[package]
name = "plumb-export"
version.workspace = true
edition.workspace = true
license.workspace = true
autobins = false

[lib]
path = "src/main.rs"

[dependencies]
plumb-syntax = { path = "../plumb-syntax" }
plumb-semantics = { path = "../plumb-semantics" }
serde_json.workspace = true

[dev-dependencies]
plumb-migrate = { path = "../plumb-migrate" }
